development:
  host: localhost
  port: 5433
  user: postgres
  password: postgres
  database: rides_api

test:
  host: localhost
  port: 5433
  user: postgres
  password: postgres
  database: rides_api
  
production:
  host: localhost
  port: 5433
  user: postgres
  password: postgres
  database: rides_api